#!/usr/bin/env python
import cv2
import os

d = 'digits'
img = cv2.imread('digits.png', cv2.IMREAD_GRAYSCALE)
ret, thres = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)
if not os.path.exists(d):
    os.mkdir(d)
for k in range(10):
    p = d + '/' + str(k)
    count = 1
    if not os.path.exists(p):
        os.mkdir(p)
    for j in range(5):
        for i in range(100):
            cv2.imwrite(p + '/' + str(count) + '.png',
                        img[(k * 5 + j) * 20:((k * 5 + j) + 1) * 20,
                            i * 20:(i + 1) * 20])
            count += 1
