#!/usr/bin/env python
# import numpy as np
import cv2


cap = cv2.VideoCapture(0)
while(True):
    ret, frame = cap.read()
    readimage = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    ret, thres = cv2.threshold(readimage, 127, 255, cv2.THRESH_BINARY)
    cv2.imshow('myimage', thres)
    s = cv2.waitKey(1) & 0xFF
    if s == ord('q'):
        break
    elif(s == ord('s')):
        cv2.imwrite('digit.png', thres)
cap.release()
cv2.destroyAllWindows()
